apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: environmental-stress
  namespace: chaos-genome
spec:
  schedule: "@every 1m"
  type: "PodChaos"
  historyLimit: 5
  concurrencyPolicy: "Forbid"
  podChaos:
    action: pod-kill
    mode: one
    selector:
      labelSelectors:
        app: "cell"
