namespace: epigenetik
image: python:3.9-slim
baseCpu: 100
baseMemory: 64

# either "clonal" or "transgenerational"
strategy: "transgenerational"

# replica count for clonal; number of independent lineages for transgenerational
count: 5